#:schema node_modules/wrangler/config-schema.json
name = "tiny-ai-worker"
main = "src/index.ts"
compatibility_date = "2024-04-19"

# You can run `pnpm run cf-typegen` to generate worker-configuration.d.ts
kv_namespaces = [
    { binding = "MY_TODO", id = "3baeeaaf4768475a9fee8f03f7866a46" }
]
